questions/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from .views import index, add, submit, QuestionIndexView, question_detail, add_answer, QuestionViewSet, AnswerViewSet, increase_score, decrease_score
from .views import tagview



from .tagview import TagView, index


router = routers.DefaultRouter()
router.register(r'questions', QuestionViewSet)
router.register(r'answers', AnswerViewSet)

app_name = 'questions'
urlpatterns = [
    url(r'^_api$', include(router.urls)),
    url(r'^$', QuestionIndexView.as_view(), name='index'),
    
    url(r'^add$', add, name='add'),  # Urls with trailing slash do not work, Think how to make it optional

    url(r'^add/submit$', submit, name='submit'),

    url(r'^questions/(?P<question_id>[0-9]+)$', question_detail, name='detail'),

    url(r'^(?P<question_id>[0-9]+)/answer$', add_answer, name='answer'),
    url(r'^add_score/(?P<question_id>[0-9]+)$',increase_score, name='increase_score'),
    url(r'^/sub_score/(?P<question_id>[0-9]+)$',decrease_score, name='decrease_score'),
    url(r'^tags$', index, name='tagIndex'),
    url(r'^tags/_api$', TagView.as_view(), name='tagIndex')

]

renderflow/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [url(r'^admin/', admin.site.urls),
               url(r'', include('questions.urls'), name='home')]

questions/models.py
from django.db import models

# Create your models here.


class Question(models.Model):
    question_title = models.CharField(max_length=250, blank=False)
    question_text = models.TextField(blank=False)
    creation_date = models.DateTimeField(auto_now=True)
    score = models.IntegerField()
    tags = models.CharField(max_length=200 )
   

class Answer(models.Model):
    answer_text = models.TextField(blank=False)
    answer_date = models.DateTimeField(auto_now=True)
    answer_score=models.IntegerField()
    question=models.ForeignKey(Question, on_delete=models.CASCADE)
   



class Tag(models.Model):
    tag_name=models.CharField(max_length=20)
    tag_description=models.TextField(default="")
    tag_count=models.IntegerField()

questions/views.py
from django.shortcuts import render, reverse, redirect
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect, JsonResponse, HttpResponseNotAllowed, Http404
from django.views import generic
import datetime
from .models import Question, Answer, Tag
import markdown
import logging
from rest_framework import viewsets
from .serializers import QuestionSerializer, AnswerSerializer

from rest_framework.decorators import api_view
from rest_framework.response import Response
# Create your views here.
logger = logging.getLogger(__name__)

def index(request):
    return render(request, 'questions\index.html')


class QuestionIndexView(generic.ListView):
    template_name = 'questions/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.all()#.order_by('-creation_date')[:5]
def add(request):
    return render(request,'questions/add.html')


def submit(request):
    if request.method == 'GET':
        return HttpResponseRedirect('questions:index')
    else:
        question = Question()
        question.question_text = request.POST['question_text']
        question.question_title = request.POST['question_title']
        question.score = 0
        question.save()
        return HttpResponseRedirect(reverse('questions:index'))


def question_detail(request, question_id):
    q = Question.objects.get(id=question_id)
    q.question_text = markdown.markdown(q.question_text)
    ans = Answer.objects.filter(question_id=question_id).order_by('-answer_date')[:10]
    context = {
        'question':q,
        'answer':ans
    }
    return render(request, 'questions/question_detail.html', context)


def add_answer(request, question_id):
    if request.method == 'GET':
        return redirect('questions:detail')
    else:
        answer = Answer()
        answer.answer_text = request.POST['answer_text']
        answer.answer_date = datetime.datetime.now()
        answer.answer_score = 0
        answer.question_id = question_id
        answer.save(force_insert=True)
        return HttpResponseRedirect(reverse('questions:index'))

@api_view(['POST'])
def increase_score(request, question_id):
    try:
        q = Question.objects.get(id=question_id)
        q.score = q.score + 1
        q.save()
        serializer = QuestionSerializer(q, many=False)
        return Response(serializer.data)
    except Question.DoesNotExist:
        raise Http404


@api_view(['POST'])
def decrease_score(request, question_id):
    try:
        q = Question.objects.get(id=question_id)
        q.score = q.score - 1
        q.save()
        serializer = QuestionSerializer(q, many=False)
        return Response(serializer.data)
    except:
        raise Http404 
             

class QuestionViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = Question.objects.all()#.order_by('-date_joined')
    serializer_class = QuestionSerializer


class AnswerViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows groups to be viewed or edited.
    """
    queryset = Answer.objects.all()
    serializer_class = AnswerSerializer

def tagview(request):
    return render(request,'questions/taglist.html')

questions/templates/questions/add.html
{% extends 'questions\master.html' %}
{% block title %}
Ask a Question - Render Overflow
{% endblock %}

{%block content%}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

 <form action="{%url 'questions:submit'  %}" method="post">
{% csrf_token %}
     <div class="question_title_row">
        <span>Title</span><input type="text" name="question_title" placeholder="Whats your programming question? Be Specific">
     </div>
     <div class="question_text_row">
         <textarea name="question_text"></textarea>
     </div>
     <script>
       var simplemde = new SimpleMDE({ autosave: {enabled:true}, status:false });
     </script>
     <div class="question_submit_row">
     <input type="submit" value="Post Your Question" class="submit_button" />
     </div>

</form>
{%endblock%}

questions/templates/questions/index.html
{% extends 'questions/master.html' %}
{%block content%}
{% if latest_question_list %}
    <div class="question_list">
    {% for question in latest_question_list %}
        <div class="question_summary">
            <div class="question_score"> Some text</div>
            <div class="question_details">
            <a href="{% url 'questions:detail' question.id %}" >{{ question.question_title }}</a>
                <p>
                    {{ question.question_text }}
                </p>
            </div>

        </div>
    {% endfor %}
    </div>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

questions/templates/questions/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{%block title%}Title{% endblock %}</title>
    {% load static%}
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-beta.2-dist/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'bootstrap-4.0.0-beta.2-dist/css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/site.css'%}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css'%}">
    <link rel="stylesheet" href="{% static 'tagEditor-1.0.10/jquery.tag-editor.css' %}" />
    {% csrf_token %}
    
</head>
<body>
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
         <div class="container">
  <a class="navbar-brand" href="#">Renderflow</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'questions:add' %}">Ask a Question</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
             </div>
</nav>
  <div class="container">
     
    <main>
  {%block content%}
  {%endblock%}
        </main>
  </div>
  <script src="https://code.jquery.com/jquery-3.2.1.min.js"  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="  crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
  <script type="text/javascript" src="{% static 'bootstrap-4.0.0-beta.2-dist/js/bootstrap.min.js'%}" ></script>
  <script type="text/javascript" src="{% static 'tagEditor-1.0.10/jquery.caret.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'tagEditor-1.0.10/jquery.tag-editor.js' %}"></script>
  <script type="text/javascript">
        // using jQuery
        var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();
        function csrfSafeMethod(method) {
            // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        $.ajaxSetup({
            beforeSend: function (xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
    </script>
    {% block script %} {% endblock %}
</body>
</html>

questions/templates/questions/question_detail.html
{% extends 'questions/master.html' %}
{% block title %}
Question - {{question.question_title}}
{% endblock %}
{%block content%}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
<div class="question_detail_title">
            {{question.question_title}}    
    </div> 
<hr/>
<div class="question_detail_answer">  
    
     <div class="score">
         <i class="fa fa-caret-up" id="vote_question_up" data-questionid="{{question.id}}" aria-hidden="true"></i>
         <span id="question_score">{{question.score}}</span>     
         <i class="fa fa-caret-down" id="vote_question_down" data-questionid="{{question.id}}" aria-hidden="true"></i>
    </div>
    <div class="question_detail_summary">
    {{question.question_text | safe}}
</div>
       
</div>
<hr/>


    {% for ans in answer %}
<div class="clearfix">
        <div class="answer_detail">
            <div class="answer_score">
                 <i class="fa fa-caret-up" aria-hidden="true"></i>
                <span>{{ans.answer_score}}</span>
                 <i class="fa fa-caret-down" aria-hidden="true"></i>
            </div>
            <div>
                {{ans.answer_text}}
            </div>
           
        </div>
    <div class="answer_info" >answered {{ans.answer_date}}</div> 
    
    </div>
<hr />
    {% endfor %}

<div class="answer_user_section">
    <div class="your_answer_label">Your Answer</div>
    <div class="youranswer">
        <!--/questions/answer/{{question.id}}-->
    <form action="{%url 'questions:answer' question.id %}" method="post">
        {% csrf_token %}
        <textarea name="answer_text"></textarea>
        <script>
        var simplemde = new SimpleMDE({ autosave: {enabled:true}, status:false });
        </script>
        <input type="submit" value="Post Your Answer" class="submit_button" />
    </form>
    
</div>
</div>

{% endblock %}

{% block script %} 
{% load static %}
<script type="text/javascript" src='{% static "js/question_detail.js"%}'></script>

{% endblock %}

questions/templates/questions/tag.html
{% extends 'questions\master.html' %}
{% block title %} Tags {% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-3">
          <h3>Tag List</h3> 
            <form method="post" action="/tags/_api">
                <input type="text" name="" />
                <input type="submit" value="Create">
            </form>
        </div>
        <div class="col-sm-9">
          <h3>Details</h3>  
        <span>
            Choose a tag on left to view details
        </span>
        </div>
    </div>
</div>
{% endblock %}
{% block script %} 
{% endblock %}

questions/templates/questions/taglist.html
{% extends 'questions/master.html' %}
{% block title%}
 Tags
{% endblock %}
{% block content%}
{% endblock %}